#!/usr/bin/env bash
set -euo pipefail

# Extract ledger state hashes from cardano-node at block boundaries.
# Designed to run on the node host where cardano-node and LedgerDB are available.
#
# Reads:   corpus/golden/{era}/blocks/*.cbor (to identify block points)
# Writes:  corpus/reference/ledger_state_hashes/{era}/*.json
# Updates: corpus/reference/ledger_state_hashes/manifest.toml
#
# Required environment variables (set on node host, never committed):
#   ADE_CARDANO_CLI            — Path to cardano-cli binary
#   ADE_NODE_SOCKET_PATH       — Path to cardano-node socket
#   ADE_CARDANO_NODE_VERSION   — e.g., "10.6.2"
#   ADE_CARDANO_NODE_GIT_REV   — e.g., "0d697f14"
#   ADE_LEDGERDB_PATH          — Path to LedgerDB directory

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GOLDEN_DIR="$REPO_ROOT/corpus/golden"
OUTPUT_DIR="$REPO_ROOT/corpus/reference/ledger_state_hashes"

# --- Fail-fast on missing env vars ---
for var in ADE_CARDANO_CLI ADE_NODE_SOCKET_PATH ADE_CARDANO_NODE_VERSION ADE_CARDANO_NODE_GIT_REV; do
    if [ -z "${!var:-}" ]; then
        echo "ERROR: Required environment variable $var is not set."
        echo "See corpus/tools/.env.example for required variables."
        exit 1
    fi
done

CARDANO_CLI="$ADE_CARDANO_CLI"
NODE_SOCKET="$ADE_NODE_SOCKET_PATH"
NODE_VERSION="$ADE_CARDANO_NODE_VERSION"
NODE_GIT_REV="$ADE_CARDANO_NODE_GIT_REV"
EXTRACTION_DATE=$(date +%Y-%m-%d)

ERAS=(byron shelley allegra mary alonzo babbage conway)
MANIFEST_FILE="$OUTPUT_DIR/manifest.toml"

cat > "$MANIFEST_FILE" << 'HEADER'
# Ledger state hash reference artifacts — provenance manifest (DC-REF-01)
# Generated by corpus/tools/extract_state_hashes.sh
# See hash_surface.md for oracle evidence discipline.
HEADER

echo "State hash extraction using cardano-node $NODE_VERSION (git rev $NODE_GIT_REV)"
echo "Socket: $NODE_SOCKET"
echo ""

TOTAL=0

for era in "${ERAS[@]}"; do
    ERA_GOLDEN="$GOLDEN_DIR/$era/blocks"
    ERA_OUTPUT="$OUTPUT_DIR/$era"

    if [ ! -d "$ERA_GOLDEN" ]; then
        echo "WARN: No golden blocks for $era (skipping)"
        continue
    fi

    mkdir -p "$ERA_OUTPUT"

    # Collect block files for this era (sorted for deterministic ordering)
    BLOCK_FILES=($(ls "$ERA_GOLDEN"/*.cbor 2>/dev/null | sort))
    BLOCK_COUNT=${#BLOCK_FILES[@]}

    if [ "$BLOCK_COUNT" -lt 3 ]; then
        echo "WARN: $era has fewer than 3 blocks ($BLOCK_COUNT), extracting all"
    fi

    # Extract state hashes for contiguous sequence
    SEQUENCE_FILE="$ERA_OUTPUT/sequence_001.json"
    echo "Extracting $era state hash sequence ($BLOCK_COUNT blocks)..."

    # Build JSON sequence using cardano-cli query tip / LocalStateQuery
    # This is a placeholder structure — actual extraction requires running
    # cardano-node with the blocks applied sequentially
    echo "  NOTE: Actual extraction requires running node with LocalStateQuery or LedgerDB reader."
    echo "  This script provides the framework — implement extraction method per hash_surface.md."

    TOTAL=$((TOTAL + BLOCK_COUNT))
done

echo ""
echo "Framework complete: $TOTAL blocks identified across ${#ERAS[@]} eras"
echo "Implement extraction per hash_surface.md oracle evidence discipline."
