#!/usr/bin/env bash
set -euo pipefail

# Extract block fields from golden CBOR blocks using cardano-cli.
# Designed to run on the node host where cardano-cli is available.
#
# Reads:   corpus/golden/{era}/blocks/*.cbor
# Writes:  corpus/reference/block_fields/{era}/*.json
# Updates: corpus/reference/block_fields/manifest.toml
#
# Required environment variables (set on node host, never committed):
#   ADE_CARDANO_CLI            — Path to cardano-cli binary
#   ADE_CARDANO_NODE_VERSION   — e.g., "10.6.2"
#   ADE_CARDANO_NODE_GIT_REV   — e.g., "0d697f14"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GOLDEN_DIR="$REPO_ROOT/corpus/golden"
OUTPUT_DIR="$REPO_ROOT/corpus/reference/block_fields"

# --- Fail-fast on missing env vars ---
for var in ADE_CARDANO_CLI ADE_CARDANO_NODE_VERSION ADE_CARDANO_NODE_GIT_REV; do
    if [ -z "${!var:-}" ]; then
        echo "ERROR: Required environment variable $var is not set."
        echo "See corpus/tools/.env.example for required variables."
        exit 1
    fi
done

CARDANO_CLI="$ADE_CARDANO_CLI"
NODE_VERSION="$ADE_CARDANO_NODE_VERSION"
NODE_GIT_REV="$ADE_CARDANO_NODE_GIT_REV"

# Verify cardano-cli exists and get version
if ! command -v "$CARDANO_CLI" &>/dev/null && [ ! -x "$CARDANO_CLI" ]; then
    echo "ERROR: cardano-cli not found at $CARDANO_CLI"
    exit 1
fi

CLI_VERSION=$("$CARDANO_CLI" --version | head -1)
echo "Using: $CLI_VERSION"

ERAS=(byron shelley allegra mary alonzo babbage conway)
EXTRACTION_DATE=$(date +%Y-%m-%d)
MANIFEST_FILE="$OUTPUT_DIR/manifest.toml"

# Start fresh manifest
cat > "$MANIFEST_FILE" << 'HEADER'
# Block field reference artifacts — provenance manifest (DC-REF-01)
# Generated by corpus/tools/extract_block_fields.sh
HEADER

TOTAL=0
FAILED=0

for era in "${ERAS[@]}"; do
    ERA_GOLDEN="$GOLDEN_DIR/$era/blocks"
    ERA_OUTPUT="$OUTPUT_DIR/$era"

    if [ ! -d "$ERA_GOLDEN" ]; then
        echo "WARN: No golden blocks for $era (skipping)"
        continue
    fi

    mkdir -p "$ERA_OUTPUT"

    for cbor_file in "$ERA_GOLDEN"/*.cbor; do
        [ -f "$cbor_file" ] || continue
        basename_noext=$(basename "$cbor_file" .cbor)
        output_json="$ERA_OUTPUT/${basename_noext}.json"
        relative_path="$era/${basename_noext}.json"
        source_block="corpus/golden/$era/blocks/$(basename "$cbor_file")"

        echo "Extracting: $source_block -> $relative_path"

        # Attempt extraction with cardano-cli
        if ! "$CARDANO_CLI" latest debug decode-block \
                --block-file "$cbor_file" > "$output_json.tmp" 2>/dev/null; then
            # Fallback: try without 'latest' subcommand
            if ! "$CARDANO_CLI" debug decode-block \
                    --block-file "$cbor_file" > "$output_json.tmp" 2>/dev/null; then
                echo "  WARN: cardano-cli failed for $cbor_file (era: $era)"
                FAILED=$((FAILED + 1))
                rm -f "$output_json.tmp"
                continue
            fi
        fi

        mv "$output_json.tmp" "$output_json"

        # Compute SHA-256
        SHA256=$(sha256sum "$output_json" | awk '{print $1}')

        # Determine protocol version from era
        case "$era" in
            byron)   PROTO_VERSION="0.0" ;;
            shelley) PROTO_VERSION="2.0" ;;
            allegra) PROTO_VERSION="3.0" ;;
            mary)    PROTO_VERSION="4.0" ;;
            alonzo)  PROTO_VERSION="6.0" ;;
            babbage) PROTO_VERSION="8.0" ;;
            conway)  PROTO_VERSION="10.0" ;;
            *)       PROTO_VERSION="unknown" ;;
        esac

        # Append manifest entry
        cat >> "$MANIFEST_FILE" << ENTRY

[[entries]]
file = "$relative_path"
source_block = "$source_block"
era = "$era"
type = "block_fields"
extraction_tool = "cardano-cli"
extraction_tool_version = "$CLI_VERSION"
extraction_tool_git_rev = "$NODE_GIT_REV"
cardano_node_version = "$NODE_VERSION"
network_magic = 764824073
protocol_version = "$PROTO_VERSION"
extraction_method = "cardano-cli debug decode-block"
extraction_date = "$EXTRACTION_DATE"
source_type = "ImmutableDB"
reproducibility = "Run cardano-cli debug decode-block --block-file on golden CBOR from mithril snapshot epoch 618"
sha256 = "$SHA256"
ENTRY

        TOTAL=$((TOTAL + 1))
    done
done

echo ""
echo "Extraction complete: $TOTAL blocks extracted, $FAILED failures"
if [ "$FAILED" -gt 0 ]; then
    echo "NOTE: Some blocks failed extraction (likely Byron). Manual extraction may be needed."
fi
echo "Manifest written to: $MANIFEST_FILE"
