// Core Contract:
// - Deterministic: same inputs + same seed => byte-identical outputs
// - No wall-clock time, true randomness, HashMap/HashSet, or floats
//
// PROPOSAL-PROCEDURES-DECODE PP-S2 (CE-PP-6): canonical synthetic
// corpus for `proposal_procedures` round-trip evidence. Each entry is
// a labeled pre-encoded byte sequence plus the typed shape it MUST
// decode to. The bytes are generated by the BLUE encoder, so they are
// canonical by construction; replay decodes them, asserts the typed
// shape, and re-encodes to confirm byte-identicality.
//
// Real-chain corpus extraction is a separate strengthening slice when
// Conway txs carrying proposals become available in the in-tree
// corpus (verified at PP-S1 HEAD: no such txs exist; OQ-5 fallback to
// synthetic canonical fixtures is the agreed close).

use std::collections::{BTreeMap, BTreeSet};

use ade_codec::cbor::{self, ContainerEncoding, IntWidth};
use ade_codec::conway::governance::{decode_proposal_procedures, encode_proposal_procedures};
use ade_types::conway::governance::{Anchor, GovAction, GovActionId, ProposalProcedure};
use ade_types::shelley::cert::StakeCredential;
use ade_types::tx::Coin;
use ade_types::{Hash28, Hash32};

/// One entry in the canonical proposal_procedures corpus.
#[derive(Debug, Clone)]
pub struct CorpusEntry {
    /// Stable human-readable label for diagnostics.
    pub label: &'static str,
    /// Pre-encoded canonical CBOR bytes for the `proposal_procedures`
    /// field (the tx-body key 20 payload).
    pub bytes: Vec<u8>,
    /// The typed shape `decode_proposal_procedures` MUST produce.
    pub expected: Vec<ProposalProcedure>,
}

/// Outcome of replaying one corpus entry through the closed decoder.
#[derive(Debug, PartialEq, Eq)]
pub enum ReplayOutcome {
    /// Decoded to the expected typed shape AND re-encoded byte-identically.
    Ok,
    /// Decoded successfully but the typed shape did not match `expected`.
    DecodeMismatch,
    /// Decode succeeded but `encode(decode(bytes))` did not equal `bytes`.
    EncodeMismatch,
    /// Decode itself errored.
    DecodeError(String),
}

/// The canonical corpus: one entry per `GovAction` variant, plus a
/// multi-variant mixed entry, plus the DC-LEDGER-10-load-bearing
/// `UpdateCommittee` with KeyHash + ScriptHash of equal 28 bytes.
pub fn canonical_corpus() -> Vec<CorpusEntry> {
    vec![
        entry("info_action_single", vec![pp(GovAction::InfoAction)]),
        entry(
            "no_confidence_with_prev",
            vec![pp(GovAction::NoConfidence {
                prev_action: Some(GovActionId {
                    tx_hash: h32(0x01),
                    index: 0,
                }),
            })],
        ),
        entry(
            "hard_fork_initiation",
            vec![pp(GovAction::HardForkInitiation {
                prev_action: None,
                protocol_version: (10, 0),
            })],
        ),
        entry(
            "treasury_withdrawals_single",
            vec![pp(GovAction::TreasuryWithdrawals {
                withdrawals: vec![(reward_account(0xe1), Coin(1_000_000))],
                policy_hash: None,
            })],
        ),
        entry(
            "parameter_change_empty_update",
            vec![pp(GovAction::ParameterChange {
                prev_action: Some(GovActionId {
                    tx_hash: h32(0x02),
                    index: 1,
                }),
                update: empty_pparams_update(),
                policy_hash: Some(h28(0x42)),
            })],
        ),
        entry(
            "new_constitution_anchor_only",
            vec![pp(GovAction::NewConstitution {
                prev_action: None,
                raw: constitution_anchor_no_scripthash(),
            })],
        ),
        entry(
            "update_committee_basic",
            vec![pp(GovAction::UpdateCommittee {
                prev_action: None,
                removed: {
                    let mut s = BTreeSet::new();
                    s.insert(StakeCredential::KeyHash(h28(0x10)));
                    s
                },
                added: {
                    let mut m = BTreeMap::new();
                    m.insert(StakeCredential::ScriptHash(h28(0x20)), 600);
                    m
                },
                threshold: (2, 3),
            })],
        ),
        // DC-LEDGER-10 cross-check: KeyHash(h) and ScriptHash(h) of
        // equal 28 bytes must remain distinct through the round-trip.
        entry(
            "update_committee_keyhash_scripthash_same_bytes",
            vec![pp(GovAction::UpdateCommittee {
                prev_action: None,
                removed: {
                    let mut s = BTreeSet::new();
                    s.insert(StakeCredential::KeyHash(h28(0x99)));
                    s.insert(StakeCredential::ScriptHash(h28(0x99)));
                    s
                },
                added: BTreeMap::new(),
                threshold: (1, 2),
            })],
        ),
        // Multi-procedure mixed set.
        entry(
            "multi_procedure_mixed_variants",
            vec![
                pp(GovAction::InfoAction),
                pp(GovAction::NoConfidence { prev_action: None }),
                pp(GovAction::HardForkInitiation {
                    prev_action: None,
                    protocol_version: (10, 1),
                }),
            ],
        ),
    ]
}

/// Replay every corpus entry through the closed decoder + encoder.
/// Returns one `(label, outcome)` per entry; an `Ok` outcome means
/// decode+re-encode are both byte-identical to the expected shape +
/// original bytes.
pub fn replay_canonical_corpus() -> Vec<(String, ReplayOutcome)> {
    canonical_corpus()
        .into_iter()
        .map(|entry| {
            let CorpusEntry {
                label,
                bytes,
                expected,
            } = entry;
            let outcome = match decode_proposal_procedures(&bytes) {
                Err(e) => ReplayOutcome::DecodeError(format!("{e:?}")),
                Ok(decoded) => {
                    if decoded != expected {
                        ReplayOutcome::DecodeMismatch
                    } else {
                        let re = encode_proposal_procedures(&decoded);
                        if re != bytes {
                            ReplayOutcome::EncodeMismatch
                        } else {
                            ReplayOutcome::Ok
                        }
                    }
                }
            };
            (label.to_string(), outcome)
        })
        .collect()
}

// ---- private fixture helpers ----

fn entry(label: &'static str, procs: Vec<ProposalProcedure>) -> CorpusEntry {
    let bytes = encode_proposal_procedures(&procs);
    CorpusEntry {
        label,
        bytes,
        expected: procs,
    }
}

fn pp(action: GovAction) -> ProposalProcedure {
    ProposalProcedure {
        deposit: Coin(100_000_000_000),
        return_addr: reward_account(0xe0),
        gov_action: action,
        anchor: canonical_anchor(),
    }
}

fn h28(b: u8) -> Hash28 {
    Hash28([b; 28])
}

fn h32(b: u8) -> Hash32 {
    Hash32([b; 32])
}

fn reward_account(byte: u8) -> Vec<u8> {
    vec![byte; 29]
}

fn canonical_anchor() -> Anchor {
    let mut buf = Vec::new();
    cbor::write_array_header(&mut buf, ContainerEncoding::Definite(2, IntWidth::Inline));
    cbor::write_text_canonical(&mut buf, "x");
    cbor::write_bytes_canonical(&mut buf, &[0xaa; 32]);
    Anchor { raw: buf }
}

fn constitution_anchor_no_scripthash() -> Vec<u8> {
    // constitution = [anchor, scripthash/null]
    let mut buf = Vec::new();
    cbor::write_array_header(&mut buf, ContainerEncoding::Definite(2, IntWidth::Inline));
    buf.extend_from_slice(&canonical_anchor().raw);
    cbor::write_null(&mut buf);
    buf
}

fn empty_pparams_update() -> Vec<u8> {
    let mut buf = Vec::new();
    cbor::write_map_header(&mut buf, ContainerEncoding::Definite(0, IntWidth::Inline));
    buf
}
